### ISSUE TITLE
fatal error on accessing Administer>Utilities>Manage Blocked IPs

### ISSUE THREAD

**Issue by annlabsmumbai** [rohit1290/spam_login_filter#3]
Sir,
I am getting a fatal error while trying  to access the manage blocked ips page. Here is the error logged. Can u please see to it?
My elgg version is 5.0.7
`[01-Nov-2023 15:56:31 Asia/Kolkata] [2023-11-01T15:56:31+05:30] ELGG.CRITICAL: Exception at time 1698834391:
elgg_normalize_url(): Argument #1 ($url) must be of type string, null given, called in D:\localweb\www\sanchar\vendor\elgg\elgg\views\default\input\form.php on line 31
  {"backtrace":[],"process_id":4040,"memory_peak_usage":"18 MB","memory_usage":"18 MB","url":"/admin/administer_utilities/manageip","ip":"127.0.0.1","http_method":"GET","server":"sanchar.dev","referrer":"https://sanchar.dev:999/admin"}
`

**Comment by rohit1290** [comment]
Thank you for reporting. Please use the latest version https://github.com/rohit1290/spam_login_filter/releases/tag/5.0.1 and let me know if you still have any issue.
